/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinUsRouteImport } from './routes/join-us'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SubjectRouteImport } from './routes/$subject'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepositoryIndexRouteImport } from './routes/repository/index'
import { Route as PeopleIndexRouteImport } from './routes/people/index'
import { Route as RepositoryRepositoryRouteImport } from './routes/repository/$repository'
import { Route as PeoplePersonRouteImport } from './routes/people/$person'
import { Route as BlogsSplatRouteImport } from './routes/blogs/$'

const JoinUsRoute = JoinUsRouteImport.update({
  id: '/join-us',
  path: '/join-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectRoute = SubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryIndexRoute = RepositoryIndexRouteImport.update({
  id: '/repository/',
  path: '/repository/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoryRepositoryRoute = RepositoryRepositoryRouteImport.update({
  id: '/repository/$repository',
  path: '/repository/$repository',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePersonRoute = PeoplePersonRouteImport.update({
  id: '/people/$person',
  path: '/people/$person',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSplatRoute = BlogsSplatRouteImport.update({
  id: '/blogs/$',
  path: '/blogs/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$subject': typeof SubjectRoute
  '/about': typeof AboutRoute
  '/join-us': typeof JoinUsRoute
  '/blogs/$': typeof BlogsSplatRoute
  '/people/$person': typeof PeoplePersonRoute
  '/repository/$repository': typeof RepositoryRepositoryRoute
  '/people/': typeof PeopleIndexRoute
  '/repository/': typeof RepositoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$subject': typeof SubjectRoute
  '/about': typeof AboutRoute
  '/join-us': typeof JoinUsRoute
  '/blogs/$': typeof BlogsSplatRoute
  '/people/$person': typeof PeoplePersonRoute
  '/repository/$repository': typeof RepositoryRepositoryRoute
  '/people': typeof PeopleIndexRoute
  '/repository': typeof RepositoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$subject': typeof SubjectRoute
  '/about': typeof AboutRoute
  '/join-us': typeof JoinUsRoute
  '/blogs/$': typeof BlogsSplatRoute
  '/people/$person': typeof PeoplePersonRoute
  '/repository/$repository': typeof RepositoryRepositoryRoute
  '/people/': typeof PeopleIndexRoute
  '/repository/': typeof RepositoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$subject'
    | '/about'
    | '/join-us'
    | '/blogs/$'
    | '/people/$person'
    | '/repository/$repository'
    | '/people/'
    | '/repository/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$subject'
    | '/about'
    | '/join-us'
    | '/blogs/$'
    | '/people/$person'
    | '/repository/$repository'
    | '/people'
    | '/repository'
  id:
    | '__root__'
    | '/'
    | '/$subject'
    | '/about'
    | '/join-us'
    | '/blogs/$'
    | '/people/$person'
    | '/repository/$repository'
    | '/people/'
    | '/repository/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubjectRoute: typeof SubjectRoute
  AboutRoute: typeof AboutRoute
  JoinUsRoute: typeof JoinUsRoute
  BlogsSplatRoute: typeof BlogsSplatRoute
  PeoplePersonRoute: typeof PeoplePersonRoute
  RepositoryRepositoryRoute: typeof RepositoryRepositoryRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  RepositoryIndexRoute: typeof RepositoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join-us': {
      id: '/join-us'
      path: '/join-us'
      fullPath: '/join-us'
      preLoaderRoute: typeof JoinUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$subject': {
      id: '/$subject'
      path: '/$subject'
      fullPath: '/$subject'
      preLoaderRoute: typeof SubjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository/': {
      id: '/repository/'
      path: '/repository'
      fullPath: '/repository/'
      preLoaderRoute: typeof RepositoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repository/$repository': {
      id: '/repository/$repository'
      path: '/repository/$repository'
      fullPath: '/repository/$repository'
      preLoaderRoute: typeof RepositoryRepositoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$person': {
      id: '/people/$person'
      path: '/people/$person'
      fullPath: '/people/$person'
      preLoaderRoute: typeof PeoplePersonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$': {
      id: '/blogs/$'
      path: '/blogs/$'
      fullPath: '/blogs/$'
      preLoaderRoute: typeof BlogsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubjectRoute: SubjectRoute,
  AboutRoute: AboutRoute,
  JoinUsRoute: JoinUsRoute,
  BlogsSplatRoute: BlogsSplatRoute,
  PeoplePersonRoute: PeoplePersonRoute,
  RepositoryRepositoryRoute: RepositoryRepositoryRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  RepositoryIndexRoute: RepositoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
